modules/wolfgame.py

We have the reaper now, and the mysterious plague does more harm than
good in bigger games.
Closes #114.

Remove the mysterious plague

---

src/events.py
src/settings.py
src/wolfgame.py

Also fixes and reenables evilvillage (as an example of how the events system can be used).

Add event system

---

src/settings.py
src/wolfgame.py

This prepares for the planned deprecation of opt-out `!ping` in favor of `!pingif`. Additionally, to make up for the removal of using `!ping` to add 30 seconds of wait time, this adds a token bucket that `!wait` uses.

!pingif advertisement

---

src/settings.py
src/wolfgame.py

This entirely removes `!ping` and all cousin features. Left in a dummy `!ping`, `!away` and `!back` to `/notice` people that it no longer exists. It doesn't do anything anymore.

Remove ping

---

src/settings.py
src/wolfgame.py

This changes a lot of the internal workings by replacing most of the lists by sets where possible. OrderedDict is used for ROLE_GUIDE, list_players now uses join order, and role_order was superseded by the ROLE_GUIDE ordering. Should be ready to merge. Needs reviewing.

Mass refactor of the data types

---

src/decorators.py
src/settings.py
src/wolfgame.py

This allows for things like making ADMINS/OWNERS take a full hostmask,
or fallowing/fdenying a full hostmask with wildcards. It also allows for
a distinction between two people that share a hostmask but have a
different ident.
stasis now checks all matching stasis and returns the highest amount
fallow/fdeny have two new options -acc and -host to explicitly specify
what type the argument is
-cmds in fallow/fdeny show commands from all matching masks, to bring it
in line with how actual allow/deny parsing works, before it would only
show the first match

Expand host-based variables to take full-on hostmasks

---

src/settings.py

<+abra0> petition to add "I'm sorry I can't do that Dave" to !ping responses  
I have no idea whether this is the real quote or not.

abra0's suggestion

---

src/wolfgame.py

update simple, notice to track ident@host for users sharing hosts

---

src/settings.py

With apologies to *The Hunt for Red October*.

Add another !ping reply

---

botconfig.py.example
oyoyo/client.py
wolfbot.py

Because oyoyo is dumb and someone might actually need PASS to actually have a real password to connect instead of just authing to nickserv

Add SERVER_PASS config to control PASS command

---

src/__init__.py
src/gamemodes.py
src/proxy.py
src/utilities.py
src/wolfgame.py

Introduce proxies as a means of breaking circular import chains

---

messages/en.json

Added a few death messages for both reveal and no-reveal.

Death msgs

---

src/wolfgame.py

Now the bot will try to get latest commit short id, and if that fails, don't include it.

Add CTCP VERSION support

---

requirements.txt
src/channels.py
src/context.py
src/users.py
wolfbot.py

Right now these don't do anything, but in the future they will be how
we'll do channel and user handling.

New IRCContext, Channel and User classes

---

src/hooks.py

Tested as a whole as part of the refactor. The bulk of the frame is done, but the smaller details will need to be fleshed out as refactoring continues.

Add a new hooks.py file

---

src/users.py
src/wolfgame.py

Nothing more or less than a change in the interface

Change the user handling calls in wolfgame.py

---

src/db.py
src/wolfgame.py

Fixes to #254 and also another issue we've had before

Fflags fix, fixes #254

---

src/gamemodes.py

Probably should fix this now that we re-enabled villagergame

Villagergame retribution fix

---

messages/en.json
src/roles/wolf.py
src/wolfgame.py

this restriction doesn't make much sense from a gameplay perspective, other roles like wolf shaman can already do both.

Allow werecrow to both observe and kill at the same time

---

messages/en.json
src/channels.py
src/decorators.py
src/dispatcher.py
src/gamemodes.py
src/handler.py
src/roles/dullahan.py
src/roles/shaman.py
src/roles/skel.py
src/roles/vengefulghost.py
src/roles/villager.py
src/roles/wildchild.py
src/users.py
src/wolfgame.py

It's actually ready to merge now, and it addresses @skizzerz's concerns.

Add a backwards-compatibility handler for commands

---

src/settings.py
src/wolfgame.py

Goat revamp

---

src/roles/angel.py
src/roles/detective.py
src/roles/doomsayer.py
src/roles/dullahan.py
src/roles/harlot.py
src/roles/hunter.py
src/roles/mystic.py
src/roles/seer.py
src/roles/shaman.py
src/roles/succubus.py
src/roles/vigilante.py
src/roles/wildchild.py
src/roles/wolf.py
src/roles/wolfcub.py
src/wolfgame.py

This converts the check_exchange event. The function has been mostly left untouched. Needs reviewing.

Convert check_exchange

---

src/gamemodes.py
src/handler.py
src/roles/angel.py
src/roles/blessed.py
src/roles/cursed.py
src/roles/detective.py
src/roles/doomsayer.py
src/roles/dullahan.py
src/roles/fallenangel.py
src/roles/hunter.py
src/roles/madscientist.py
src/roles/mayor.py
src/roles/mystic.py
src/roles/seer.py
src/roles/shaman.py
src/roles/succubus.py
src/roles/traitor.py
src/roles/vengefulghost.py
src/roles/vigilante.py
src/roles/villager.py
src/roles/wildchild.py
src/roles/wolf.py
src/roles/wolfcub.py
src/wolfgame.py

What it says on the tin. Also some other cleanup elsewhere because having unrelated things in a PR is a requirement here.

Convert del_player to Users

---

messages/en.json

Change villagergame win message

---

messages/en.json
src/settings.py
src/utilities.py
src/wolfgame.py

Adds more configurability to spectate, spectate is now a separate flag from revealroles and you can configure it to send a notice to the spectated chat when someone does it

Spectate changes

---

src/decorators.py
src/hooks.py
src/users.py
src/wolfgame.py

Also don't track disconnected users by nick anymore. But that seems less
major than fixing the docstring.

convert var.DISCONNECTED to users

---

src/wolfgame.py

Move those commands to use the `@command()` decorator instead of the legacy `@cmd()` one.

!coin, !cat, !pony

---

src/roles/vigilante.py

Fully tested, works as expected.

Convert vigilante

---

messages/en.json
src/wolfgame.py

Adds the following:
The remains of one of the village pigs are found.
A few bones from a local squirrel are found.
The imprint of a wolf faceplanting is found near the village square.

Adds 3 more "No Victim" Messages

---

.gitignore
botconfig.py.example
oyoyo/client.py
src/handler.py
src/settings.py
wolfbot.py

See #301 for comments and stuff that still need to be worked on

Support for TLS certificate verification and client certificates redux

---

src/utilities.py
src/wolfgame.py

Issue #255

---

src/gamemodes.py
src/roles/piper.py
src/roles/succubus.py
src/roles/traitor.py
src/roles/villager.py
src/roles/wolfcub.py
src/wolfgame.py

What it says. It's been tested and is pretty straighforward.

Remove the cli argument from chk_win

---

src/handler.py
src/hooks.py

Add proper support for CHGHOST, and also get rid of some misguided assumptions in the hooks.

Add support for CHGHOST

---

messages/en.json
src/wolfgame.py

improve frole template handling, don't require underscores

---

messages/en.json
src/roles/wolf.py

Notifies the wolves that they have minions, without telling them who they are.
Split from #325

Send "has_minions" message to wolves.

---

messages/en.json
src/roles/_mystic_helper.py
src/roles/_shaman_helper.py
src/roles/angel.py
src/roles/assassin.py
src/roles/augur.py
src/roles/crazedshaman.py
src/roles/detective.py
src/roles/doomsayer.py
src/roles/dullahan.py
src/roles/harlot.py
src/roles/hunter.py
src/roles/investigator.py
src/roles/oracle.py
src/roles/piper.py
src/roles/seer.py
src/roles/shaman.py
src/roles/succubus.py
src/roles/vengefulghost.py
src/roles/vigilante.py
src/roles/wolf.py
src/roles/wolfshaman.py
src/settings.py
src/wolfgame.py

Tested thanks to Iciloo, ready to merge!

Overhaul succubus

---

src/gamemodes.py

Remove 4p mudkip

---

src/functions.py
src/roles/_mystic_helper.py
src/roles/clone.py
src/wolfgame.py

This splits and converts clone. Fully tested.

Split and convert clone

---

src/db.py

Mostly motivated by https://werewolf.chat/leaderboard/ listing only people with 200+ games

Add total winrate output to !p

---

src/wolfgame.py

remove deadlink

---

src/roles/_mystic_helper.py
src/roles/priest.py
src/roles/vengefulghost.py
src/wolfgame.py

I didn't add support for exchanging in the role file, seeing as we've disabled that feature for now. It doesn't have any state it should care about during role setup.

Split and convert priest

---

messages/en.json
src/wolfgame.py

Changes the `"player_joined"` message in `messages/en.json` to a list of 10 unique messages and adds the appropriate code to `wolfgame.py` so a random message is chosen each time a player joins.

Added random join messages

---

src/decorators.py
src/roles/assassin.py
src/roles/crazedshaman.py
src/roles/doomsayer.py
src/roles/hag.py
src/roles/helper/shamans.py
src/roles/helper/wolves.py
src/roles/shaman.py
src/roles/vengefulghost.py
src/roles/wolfshaman.py
src/status/silence.py
src/wolfgame.py

Fully tested, this was the final status that hadn't been converted yet

Add the new Silent status

---

botconfig.py.example
src/__init__.py
src/decorators.py
src/settings.py

Also remove PASTEBIN_ERRORS preference and unconditionally submit errors to us

Switch pastebin service to ww.chat

---

src/gamemodes/evilvillage.py
src/gamemodes/villagergame.py
src/wolfgame.py

- Fool can win again in evilvillage
- !time now reports the proper amount after all safes act in villagergame but before night ends
- Night can no longer exceed the regular time limit in villagergame

Timer fixes

---

src/roles/angel.py

Untested as of now. Fixes #390.

Avoid displaying duplicate message when guarding self and getting killed by fallen angel

---

src/users.py

Since apparently IRC doesn't let us have nice things.
Not merging yet since maybe we want to rework how we handle stale account info on ircds without account-notify as well.

Make sure the bot knows about itself

---

messages/en.json

* https://i.redd.it/dstee514i5zz.jpg
* https://i.imgur.com/jWFy9aV.gifv
* https://i.imgur.com/aK34qpZ.gifv

Add new 🐺 pictures

---

src/status/forcevote.py
src/votes.py
src/wolfgame.py

Added a new method, to get the list of all players who are unable to abstain. Then used the same logic that's used to prevent forced abstainers from voting

Fix being able to abstain while having impatience totem

---

messages/en.json

Idea by Iciloo @ freenode, doing it on her behalf.

Add guillotine lynch message

---

src/dispatcher.py

Allow replies to non-players to go to channel in join phase

---

README.md

Update README.md with the following changes:
- Minimum player count is now 6
- Bot configuration is now YAML-based (and also extensively commented, so I nixed a lot of the helptext previously here)
- Additional gameplay settings not in the example config file are on the wiki
- The gamemode template file went AWOL so suggest looking at existing gamemodes and the community modes instead
- Lagcheck is gone

Update README.md for YAML config and other new stuff
