modules/wolfgame.py, settings/wolfgame.py
Adds a setting to disallow quitting for a few seconds after the game started to prevent accidents with people doing `!quit` when they don't want to quit *during* the actual game for some reason.
This happens every now and then; might be a good idea to have a method to avoid it.
=> Disallow !quit immediately after starting to avoid accidents

modules/common.py, modules/wolfgame.py, settings/wolfgame.py, tools/decorators.py
This change gets entirely rid of PM commands decorators and adds a number of switches to the decorators. A number of new parameters were added to the decorators and a lot of cluster was removed from the functions themselves (they are now in the decorators).
The `chan` (Default: `True`) and `pm` (Default: `False`) parameters can be used to define if a command should be used as a channel and/or PM command. Parameters given to the functions are the same as before: `cli, nick, chan, rest` and PM commands are `cli, nick, nick, rest` to ensure that always 4 parameters are fed. The `game`, `join`, `none` and `playing` parameters were also added. More info below. The `roles` parameters (defaulting to an empty tuple) expects a tuple, although a list or set will also work. They are used to …
=> Huge overhaul to the decorators (+ a lot of small changes).

modules/wolfgame.py, settings/wolfgame.py
The only roles that should NOT be assassin are roles that the other team
MUST kill in order to have a good shot at winning. Therefore, we don't
need to have so many saferoles unable to be assassin, as well as certain
neutral roles. The current list is as follows:
- wolves + traitor, since these all need to die for village to win
- lycan, because if turned they need to die for village to win
- seer/oracle/harlot/augur/detective, capable of making safes so wolves
need to focus on killing them in order to have a shot at winning
- bodyguard/GA, capable of preventing other safes from dying, again need
to die for wolves to have a shot at winning
Everyone else is fair game, including shaman, drunk, hunter, doctor,
crazed shaman, and fool (who were all previously restricted).
If drunk is …
=> Remove some restrictions on who can be assassin

modules/wolfgame.py, settings/wolfgame.py
Allows ops to easily synchronize the actual channel modes with the bot's view of what they should be. Could be easily extended to call this automatically when servers reset modes on netjoin; I'll look into that tomorrow.
=> fsync command

modules/wolfgame.py, settings/wolfgame.py
This adds a `!pingif` (and a few aliases, such as `!pingat` and `!pingme`) command to lykos. People who pick this option will see themselves added to the !ping list, regardless of their !away status, when the amount of players reaches or exceeds their preferences. `!pingif` can also be used to set how they want to be pinged (either right away when the sufficient amount of players have joined, added to the ping list but not pinged, or both). The bot will ping all players it can roughly 10 seconds after the last !join; this is done to reduce unnecessary who requests and pingspamming, which could cause both lag and annoyance. This is done through a separate thread, started when the first player joins, which exits when the game starts or the last player quits.
This is pretty much ready to …
=> Add the new ping-if feature.

src/decorators.py, src/handler.py, src/wolfgame.py
Old decorators were silly and stupid, and we certainly did not need a generator for these. Moreover, it was a bunch of intrinsic namespace mangling, which we try to avoid as much as possible. I change those to be classes, so this means they are more customizable and less namespace-mangled-restricted-whatever. This works fine, waiting on other people's suggestions.
=> Change decorators

src/settings.py, src/wolfgame.py
This commit adds 3 new roles and changes the semantics of
kills/protections to work more like the impatience and pacifism totems.
- Add mystic and wolf mystic roles which can divine the number of
players still alive on the opposing team each night. These roles are
meant for games where role reveal is off as !stats gives the same info
otherwise.
- Add fallen angel which is a corrupted version of the guardian angel,
created when a guardian angel is bitten by alpha wolf. This role is
incredibly potent as they bypass all forms of protection on their
target. GAs corrupted this way also automatically gain the assassin
template.
- Protections/kills now stack and cancel each other out. As such, 2
kills but only 1 protection will result in the kill still happening.
- Fix help text for active alpha …
=> New roles, protection semantics, and alpha fixes

src/settings.py, src/wolfgame.py
Decoupled ROLE_REVEAL from impacting !stats, added new STATS_TYPE.
ROLE_REVEAL is now a string:
- on = roles revealed on death
- off = roles not revealed on death
- team = user's team revealed on death but not their role
STATS_TYPE is also a string:
- default = stats are calculated as if a villager or nonplayer was
manually tracking who was what; this leads to !stats not revealing
any information that is not publicly known
- accurate = what it used to be with a couple modifications; all roles
are shown (VG and time lord are no longer lumped with villager),
alpha wolf and lycans turning are hidden, nothing else is hidden
(so you can see what amnesiac turned into or when clone turns)
- team = only shows number of people on each team, calculated the same
way as accurate
- disabled = stats …
=> !stats Overhaul

src/settings.py, src/wolfgame.py
Pretty much what it says in the title. Changes `wolfgame.py` to require at least `floor((num_players + 1) / 2.2)` to start, with an upper limit of 4.
Players | Votes<br />required
:---------:|:------------------:
4-5        | 2
6-10      | 3
>= 11    | 4
=> Require a minimum number of votes to start a game

src/wolfgame.py
When players part and rejoin during the night phase when `DEVOICE_DURING_NIGHT = True` the bot revoices them. This fixes that.
=> Fix voicing on rejoin at night when devoice during night is enabled

src/wolfgame.py
Seeing other players' commands in deadchat can get really annoying with everyone doing `revealroles`. This hides command starting with ! so at least you can choose to not spam everyone else.
=> Hide commands in deadchat

oyoyo/client.py
Reverts lykoss/lykos#204
[2015-12-05 00:47:01+0000] Traceback (most recent call last):
File "./wolfbot.py", line 71, in <module>
main()
File "./wolfbot.py", line 64, in main
stream_handler=src.stream,
File "/home/lykos/lykos/oyoyo/client.py", line 126, in __init__
self.socket = ssl.wrap_socket(self.socket)
File "/usr/lib/python3.4/ssl.py", line 887, in wrap_socket
ciphers=ciphers)
File "/usr/lib/python3.4/ssl.py", line 525, in __init__
if sock.getsockopt(SOL_SOCKET, SO_TYPE) != SOCK_STREAM:
AttributeError: 'NoneType' object has no attribute 'getsockopt'
=> Revert "Support IPv6 connections"

src/roles/mayor.py, src/roles/shaman.py, src/wolfgame.py
Also adjust revealing totem so that it always fires after mayor, in case
someone has both. Before it would depend on the order the files were
imported, which could lead to oddities down the road.
This fixes #256
=> Split mayor

src/wolfgame.py
In join phase, `var.PLAYERS` is empty, so `var.ALL_PLAYERS` needs to bechecked instead.
(While I'm at it, changed it to `<= 9` rather than `< 10`, just for consistency with the rest of the code.)
Fixes #263.
=> Fix villagergame appearing above 9p

src/roles/traitor.py, src/utilities.py, src/wolfgame.py
As part of this, adjust team and accurate stats to no longer hide any
information. For team stats in particular, it was very misleading to
list traitor as villager, because it gives the village the impression
they have more time than they actually do (i.e. 2 wolfteam 5 vilteam
actually means 3 wolfteam 4 vilteam but that is not obvious). As team
stats were changed, team reveal was also changed to disregard hidden
traitor, so that the two can't be correlated to pick out if traitor died
(if traitor was revealed as vilteam but stats decremented wolfteam, that
would guarantee that traitor died).
Also commit groundwork for the stats rewrite, hidden behind an
"experimental" stats type (so it is not on by default). It is still very
WIP, many things do not yet work with it.
=> Split traitor

messages/en.json
20:01:04 <+nyuszika7h> "beaky played Russian roulette, and lost"
20:01:10 <+nyuszika7h> I don't think there should be a comma there
20:01:58 <+nyuszika7h> idk though
20:02:04 <+nyuszika7h> it seems weird, though that's not a list of things
=> Removed comma in "... played Russian roulette, and lost"

src/decorators.py, src/gamemodes.py, src/handler.py, src/roles/angel.py, src/roles/detective.py, src/roles/doomsayer.py, src/roles/dullahan.py, src/roles/hunter.py, src/roles/seer.py, src/roles/shaman.py, src/roles/vengefulghost.py, src/roles/vigilante.py, src/roles/wildchild.py, src/roles/wolf.py, src/warnings.py, src/wolfgame.py
The argument should be `True` for all commands until the new interface is implemented, at which point I'll begin updating the calls. Until then, there's absolutely no change in functionality whatsoever.
(I checked that all commands had it with a simple `assert old_api` in `cmd.__init__`)
=> Add a transition method for the old->new interface

src/channels.py, src/users.py
Weak references would normally be great, except Python does not specify behavior for garbage collection (indeed, having a gc at all is optional), and not all gc's do reference counting. This means the weak reference to a user may not be cleared in a reasonable amount of time (or ever), which causes subtle bugs.
=> Kill weakrefs

src/utilities.py
When a game is being played with team reveal instead of role reveal, use explicit team names instead of just "wolf" or "villager" to make it clear that we're referencing teams, not the similarly-named roles.
=> In team reveal, be more clear about team names

messages/en.json, src/decorators.py, src/handler.py, src/settings.py, src/wolfgame.py, wolfbot.py
Also allow prefixing commands by their role name to remove ambiguity
should a person be multiple roles. For example, "seer see foo" and
"augur see foo" will now work if a person is both seer and augur
(whereas normal see foo would be ambiguous). A player will be directed
to use the unambiguous prefixed version if we detect that a role command
will fire multiple times for them.
For sanity reasons, these role prefixes are implemented as exclusive
commands, meaning no other commands or command aliases may use the same
name. Clone needs to be special-cased in this regard, as clone is both a
role name and a command name.
=> Make potato an alias for villager

src/gamemodes.py, src/roles/angel.py, src/roles/blessed.py, src/roles/doomsayer.py, src/roles/dullahan.py, src/roles/fallenangel.py, src/roles/harlot.py, src/roles/hunter.py, src/roles/shaman.py, src/roles/succubus.py, src/roles/vengefulghost.py, src/roles/vigilante.py, src/roles/wildchild.py, src/roles/wolf.py, src/roles/wolfcub.py, src/wolfgame.py
Convert most of the transition_day function, and all of its events (as well as all the events it eventually fires) to no longer use cli and be user-aware. Has been fully tested thanks to Iciloo. Awaiting @skizzerz's review.
=> Convert transition_day

messages/en.json, src/wolfgame.py
If the user rejoins as a different user, the ghost stuck around and
broke things. This fixes that. It also makes it smarter when rejoining
as a different nick, and alerts what the old nick was in such cases.
=> Fix return_to_village for disconnected users

src/channels.py, src/context.py, src/decorators.py, src/dispatcher.py, src/functions.py, src/gamemodes.py, src/roles/angel.py, src/roles/blessed.py, src/roles/cursed.py, src/roles/detective.py, src/roles/dullahan.py, src/roles/harlot.py, src/roles/hunter.py, src/roles/madscientist.py, src/roles/mayor.py, src/roles/shaman.py, src/roles/traitor.py, src/roles/vigilante.py, src/roles/wildchild.py, src/roles/wolf.py, src/users.py, src/utilities.py, src/wolfgame.py
This gets rid of the (dced) hack, with var.DCED_LOSERS taking its place.
Succubus was not touched, as there is already a PR which converts it,
although the succubus events in other files were touched.
Some sites were updated to be (more) Users-aware, while others replaced
it with an old deprecated get_roles() API. As more things get converted,
these will hopefully get eliminated as well. A FIXME comment was added
to all such occurrences.
=> Convert var.ROLES and var.ORIGINAL_ROLES to Users

.gitignore, oyoyo/client.py, src/settings.py, src/wolfgame.py, wolfbot.py
If a TLS certificate fingerprint is provided, the client will check it against the SHA256 hex digest of the server's certificate. Different hash algorithms can be specified, and multiple fingerprints can be specified for networks with more than one server.
Not sure if `print()` is the right thing to do within the `connect()` method in order to display to the user when certificate validation fails.
=> Support for TLS certificate verification and client certificates.

messages/en.json
"-lykos- You cannot use this command in channel right now" doesn't looks good compared to the rest of lykos messages.
=> Add missing dot

src/wolfgame.py
Roles defined for lower counts are automatically merged into the lowest player count that is allowed in the botconfig.
=> Don't show counts less than MIN_PLAYERS in !roles

src/defaultsettings.yml
This was changed to 1:00 with the refactor, which made it not match the language of the warning message sent to the channel ("the night is almost over").
Fixed #489
=> Set default for night warning timer back to 1:30

src/roles/piper.py
The win condition for piper checked whether the current phase was "day". This meant that games that ended on the day transition (e.g. the last uncharmed player got charmed overnight) weren't resolving properly if other roles' win conditions triggered on the same transition (e.g. wolves killed enough people to win at the same time). Additionally, if other roles didn't have a win condition, the game would transition fully to day (lynch instructions and all) and then end the game, which looked odd.
Back in ye olden days, this check was needed because charmings were applied immediately (i.e. without the check, a game might end right after the piper charmed, because all players would then be charmed). However, a separate variable TOBECHARMED now holds newly-charmed players during night and …
=> Remove day phase check from piper win condition

src/users.py
the code as it currently is won't clean up a user when they part the only channel they share with lykos, which means if they rejoin with different details (i.e. changed ident) there will be a version of them still in state (but in no channels!) which causes `users.py::get()` to find multiple potential users
=> still prune users from state when there's no active game

src/roles/angel.py
This stops GA from double-counting as having done their role (meaning that someone else's roll action can get skipped) for purposes of night ending.
Fixes #514
Tested in debug mode using the transcript in 514, seems to work fine.
=> Clear PASSED when GA guards

src/gamemodes/__init__.py, src/roles/matchmaker.py, src/users.py
This gets rid of a lot of nested loops by making proper use of the adjacency list datastructure already in place to traverse through the lovers graph. A second graph containing forward edges only is maintained for revealroles and endgame display, so that the main lovers graph can be pruned as people die and therefore simplify a lot of other logic.
For the second graph, we map in order of lower accountname to higher accountname, since this is guaranteed to be stable throughout the course of a game.
=> Clean up lover logic

src/__init__.py, src/functions.py, src/gamestate.py, src/locations.py, src/pregame.py, src/roles/alphawolf.py, src/roles/doomsayer.py, src/roles/harlot.py, src/roles/helper/gunners.py, src/roles/helper/shamans.py, src/roles/helper/wolves.py, src/roles/priest.py, src/roles/succubus.py, src/status/dying.py, src/trans.py
This is a significantly lighter refactor than #518. To wit,
- The absent status remains. We move people to the square or their house depending on their absent status at beginning of day, but otherwise location during daytime does not impact ability to vote by itself.
- Locations are singleton objects based on their name and do not carry any game state in the object itself. All game state is stored in GameState itself.
- There are no location subclasses; everything is just directly a Location.
- All access to location data is done via the locations APIs rather than directly modifying the GameState variables. This allows for easier future refactors of how we are storing data.
=> Refactor locations (version 2)

botconfig.example.yml, gendoc.py, src/config.py, src/defaultsettings.yml, src/gamemodes/__init__.py, src/gamemodes/aleatoire.py, src/gamemodes/alpha.py, src/gamemodes/boreal.py, src/gamemodes/charming.py, src/gamemodes/classic.py, src/gamemodes/default.py, src/gamemodes/drunkfire.py, src/gamemodes/evilvillage.py, src/gamemodes/foolish.py, src/gamemodes/guardian.py, src/gamemodes/kaboom.py, src/gamemodes/lycan.py, src/gamemodes/mad.py, src/gamemodes/maelstrom.py, src/gamemodes/masquerade.py, src/gamemodes/mudkip.py, src/gamemodes/noreveal.py, src/gamemodes/pactbreaker.py, src/gamemodes/random.py, src/gamemodes/rapidfire.py, src/gamemodes/sleepy.py, src/gamemodes/valentines.py, src/pregame.py, src/votes.py
Rather than encoding the likelihood of a mode as part of the game_mode decorator, it is now present in botconfig.yml. The defaults have been migrated over, however any custom modes will require manual work.
If your custom mode simply re-defined a built-in mode to change the likelihood, delete the custom mode file and customize the likelihood via botconfig.yml instead.
If you have actual custom modes, you must remove the likelihood kwarg from the game_mode decorator, and then add a section to your botconfig.yml to define the mode's likelihood, like so:
```yml
gameplay:
<mode name>:
weight: <likelihood>
```
The default is 0 for custom modes that are missing from botconfig, i.e. the modes will be majority-vote only. Failure to remove the likelihood kwarg will result in the bot failing to …
=> (BREAKING CHANGE) Make likelihoods configurable
